PACKAGE_NAME="open-volar-s"
PACKAGE_VERSION="0.9.5"
BUILT_MODULE_NAME[0]="open_volar_s_usb"
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb/misc"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean KDIR=/lib/modules/${kernelver}/build"
